name: flexberry_flutter_sample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_feather_icons: ^2.0.0
  go_router: ^14.0.2
  openapi_generator_annotations: ^5.0.2
  built_collection: ^5.1.1
  intl: ^0.19.0
  backend:
    path: api/backend

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  openapi_generator: ^5.0.2
  openapi_generator_cli: ^5.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
